### ISSUE TITLE
CI actions

### ISSUE THREAD

**Issue by 20jasper** [coding-after-hours/SDSGAS#14]
Create an action to run CI to run on push to main and on PR to main

- [x] set a timeout for the job
- [x] checkout repo
- [x] install node
- [x] install dependencies
- [x] linter
- [x] formatter
- [x] tests

**Comment by Brandon-Schefstad** [comment]
```yml
on:
  push:
    branches:
      - 'main'
```
