### ISSUE TITLE
Add CRON to services

### ISSUE THREAD

**Issue by 20jasper** [coding-after-hours/SDSGAS#3]
Schedule Lambda  to run every Wednesday @ 6:30 PM EST with CRON

We need to add an event rule and a permission to invoke the lambda

SAM example
```yaml
RefreshPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref YourLambda
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt YourLambdaEventRule.Arn

 YourLambdaEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Scheduled Rule
      Name: String
      # Mins, hours, day-of-month, month, day-of-week, year
      # this example runs every sunday at 12AM utc
      ScheduleExpression: "cron(0 0 ? * SUN *)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt YourLambdaFunction.Arn
          Id: targetFunction1

```
> **Warning** 
> Lambdas may not run exactly on the time, so we should look into how to tighten the window

Resources:

- [Chron expression maker](https://www.freeformatter.com/cron-expression-generator-quartz.html)
- [AWS Lambda w/ EventBridge](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-run-lambda-schedule.html)
